server:
  port: 10162
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot
    username: root
    password: 111111
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    properties:
      hibernate:
        hbm2ddl.auto: update
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  show-sql: true

  mail:
    host: smtp.163.com #邮箱服务器地址
    username: zhouyuan2452008648@163.com #用户名
    password: 522724199207zya    #密码
    default-encoding: UTF-8
  #国际化
  messages:
    basename: i18n.mess
mail:
  fromMail:
    addr: zhouyuan2452008648@163.com  #以谁来发送邮件