server:
  port: 8080

spring:
    datasource:
        name: test
        url: jdbc:mysql://192.168.13.128:3306/springboot?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
        username: test
        password: 123456
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        maxOpenPreparedStatements: 20

mybatis:
  type-aliases-package: com.study.springboot.model
  mapper-locations    : classpath:mybatis/mapper/*.xml

#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

#swagger 配置
server:
  context-path: /swagger
swagger:
  enable: true


spring:
  mail:
    host: smtp.exmail.qq.com #邮箱服务器地址
    username: 2452008648@qq.com #用户名
    password: love201314    # 密码
    default-encoding: UTF-8

mail:
  fromMail:
  addr: 2452008648@qq.com #以谁来发送邮件