server:
    port: 10161
    context-path: /svc-monitor/ #统一为访问的url加上一个前缀

spring:
  datasource:
      url: jdbc:mysql://localhost:3306/springboot
      username: root
      password: 111111
      driver-class-name: com.mysql.jdbc.Driver

  jpa:
    properties:
        hibernate:
          hbm2ddl.auto: update
          dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  show-sql: true
